project_id: "accuknox-cnapp"
clusters:
  - name: "devops-test-cluster"
    cluster_id: "devops-test-cluster"  
    node_pool_id: "test-nodes"        
    scale_up_count: 3                   
    scale_down_count: 1
    location: "us-central1"
