clusters:
  - name: "your-gke-cluster-name"
    cluster_id: "your-gke-cluster-id"  
    node_pool_id: "default-pool"        
    scale_up_count: 3                   
    scale_down_count: 1                  
