name: Use DO and GCP Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  use-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use DigitalOcean User Secret
        env:
          DO_USER: ${{ secrets.DO_USER }}
        run: |
          echo "Using DigitalOcean user: $DO_USER"
      
      - name: Decode and Use GCP Credentials
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" | base64 --decode > gcp_credentials.json
          echo "Decoded GCP credentials for use."
        