name: AccuKnox DAST Scan Workflow

on:
  schedule:
    - cron: '0 0 * * *'   # every day at 12:00 AM UTC
  workflow_dispatch:       # manual trigger option
  push:
    branches:
      - main
jobs:
  dast-scan:
    runs-on: ubuntu-latest
    continue-on-error: true  
    strategy:
      max-parallel: 1
      matrix:
        target_url:
          - "https://app.dev.accuknox.com"
          - "https://app.stage.accuknox.com"
          - "https://app.demo.accuknox.com"
          - "https://app.accuknox.com"
          - "https://app.xcitium.accuknox.com"
          - "https://app.in.accuknox.com"
          - "https://app.nrs.accuknox.com"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run AccuKnox DAST Scan
        uses: accuknox/dast-scan-action@v1.0.0
        with:
          target_url: ${{ matrix.target_url }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          tenant_id: ${{ secrets.TENANT_ID }}
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          label: "DastScan"
          severity_threshold: "High"
          scan_type: "baseline"
