name: Scale GKE Node Pools Dynamically

on:
  # schedule:
  #   - cron: '30 14 * * 5'  # At 8:00 PM IST (2:30 PM UTC) every Friday (scale down)
  #   - cron: '0 2 * * 1'     # At 7:30 AM IST (2:00 AM UTC) every Monday (scale up)
  push:
    branches:
      - main  

jobs:
  scale-gke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq for YAML parsing
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Give execute permission to the script
        run: chmod +x ./GKE/scale_gke.sh
      
      - name: Set up GCP credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > gcp-key.json
          # Check if the file was created
          ls -l gcp-key.json
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Scale down node pools
        if: github.event_name == 'push'  
        env:  
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          cd GKE  
          ./scale_gke.sh scale-down
  
      # - name: Scale up node pools
      #   if: github.event.schedule == '0 2 * * 1'
      #   env:  
      #     GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      #   run: |
      #     cd GKE  
      #     ./scale_gke.sh scale-up
