name: Scale DOKS Node Pools Dynamically

on:
  schedule:
    # Scale up every day at 5:05 PM IST (11:35 AM UTC)
    - cron: "35 11 * * *"
    # Scale down every day at 5:10 PM IST (11:40 AM UTC)
    - cron: "40 11 * * *"

jobs:
  scale-doks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq for YAML parsing
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Give execute permission to the script
        run: |
          chmod +x scale_doks.sh

      - name: Scale down node pools (scheduled)
        if: github.event.schedule == '40 11 * * *'
        run: |
          ./scale_doks.sh scale-down

      - name: Scale up node pools (scheduled)
        if: github.event.schedule == '35 11 * * *'
        run: |
          ./scale_doks.sh scale-up
