name: Scale DOKS Node Pools Dynamically

on:
  schedule:
    # Scale down every day at 10:27 AM IST (4:57 AM UTC)
    - cron: "32 11 * * *"
    # Scale up every day at 10:32 AM IST (5:02 AM UTC)
    - cron: "37 11 * * *"

jobs:
  scale-doks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq for YAML parsing
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Give execute permission to the script
        run: |
          chmod +x scale_doks.sh

      - name: Scale down node pools (scheduled)
        if: github.event.schedule == '55 22 * * *'
        run: |
          ./scale_doks.sh scale-down

      - name: Scale up node pools (scheduled)
        if: github.event.schedule == '0 23 * * *'
        run: |
          ./scale_doks.sh scale-up
