name: Scale DOKS Node Pools Dynamically

on:
  schedule:
    # Scale down every day at 5:15 PM GMT
    - cron: "15 17 * * *"
    # Scale up every day at 5:20 PM GMT
    - cron: "20 17 * * *"

jobs:
  scale-doks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq for YAML parsing
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Give execute permission to the script
        run: |
          chmod +x scale_doks.sh

      - name: Scale down node pools (scheduled)
        if: github.event.schedule == '15 17 * * *'
        run: |
          ./scale_doks.sh scale-down

      - name: Scale up node pools (scheduled)
        if: github.event.schedule == '20 17 * * *'
        run: |
          ./scale_doks.sh scale-up
