name: Scale DOKS Node Pools Dynamically

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches:
      - main

jobs:
  scale-down:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq for YAML parsing
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          chmod +x /usr/bin/yq

      - name: Give execute permission to the script
        run: |
          chmod +x ./scale_doks.sh

      - name: Scale down node pools
        run: ./scale_doks.sh scale-down

  # scale-up:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Install yq for YAML parsing
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y wget
  #         wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
  #         chmod +x /usr/bin/yq

  #     - name: Give execute permission to the script
  #       run: |
  #         chmod +x ./scale_doks.sh

  #     - name: Scale up node pools
  #       run: ./scale_doks.sh scale-up
