name: Scale DOKS Node Pools Dynamically

on:
  schedule:
    # Scale down every day at 5:25 PM IST (11:55 AM UTC)
    - cron: "55 11 * * *"
    # Scale up every day at 5:30 PM IST (12:00 PM UTC)
    - cron: "0 12 * * *"

jobs:
  scale-doks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq for YAML parsing
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Give execute permission to the script
        run: |
          chmod +x ./scale_doks.sh

      - name: Scale down node pools (scheduled)
        if: github.event.schedule == '55 11 * * *'
        run: |
          ./scale_doks.sh scale-down

      - name: Scale up node pools (scheduled)
        if: github.event.schedule == '0 12 * * *'
        run: |
          ./scale_doks.sh scale-up
